import '@/styles/globals.css'

import type { Metadata } from 'next'

import { ClerkProvider } from '@clerk/nextjs'

import { fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
	return (
		<ClerkProvider>
			<html
				lang="en"
				suppressHydrationWarning
			>
				<body
					className={cn(
						'min-h-screen bg-background font-sans antialiased',
						fontSans.variable
					)}
				>
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
