import '@/styles/globals.css'

import type { Metadata } from 'next'

import { ClerkProvider } from '@clerk/nextjs'

import { Toaster } from 'sonner'

import { fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/providers/theme-provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
	return (
		<ClerkProvider>
			<html
				lang="en"
				suppressHydrationWarning
			>
				<body
					className={cn(
						'min-h-screen bg-background font-sans antialiased',
						fontSans.variable
					)}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
						<Toaster closeButton />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
